### ISSUE TITLE
Can't place error messages in correct position

### ISSUE THREAD

**Issue by simcast** [DFE-Digital/govuk_design_system_formbuilder#126]
Hi,

The GOV.UK design system says error messages should be placed after the text and above the input e.g.

![image](https://user-images.githubusercontent.com/51447972/81913095-67c1b500-95c7-11ea-8f17-ebbe3f73e46d.png)

However when using injected content that includes paragraphs and form elements the error message appears above them.

Example from service: 
![image](https://user-images.githubusercontent.com/51447972/81912973-3ba63400-95c7-11ea-9910-77ca5eaa3a17.png)

Note: the current code works for most situations, as fixed by #110 . But in the situation described above, the preferred error placement is not possible. Is there any way it could be updated to allow this? Hope I've described this accurately.

**Comment by peteryates** [comment]
Strange, are you definitely on the latest version of the gem?

[Looking at the code](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/elements/date.rb#L26) the error message is immediately above the date input.

**Comment by simcast** [comment]
Yep we're on the latest version. This happens when using #govuk_radio_buttons_fieldset with injected revealing form elements. The one in that example uses #govuk_collection_radio_buttons and works fine as there are no revealing form elements injected.

**Comment by peteryates** [comment]
Ah sorry, I looked at the date helper (top screenshot) instead of the radio fieldset being referenced in the bottom one.

This is actually quite a difficult thing to do because the passed-in block is rendered directly, it's not amended or interfered with by the form builder at all.

In theory this could be worked around by allowing people to manually specify where they want the error message to be rendered. This would require:
* the toggling of the [built-in error message](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/containers/radio_buttons_fieldset.rb#L24)
* a new helper method to add individual error messages
* users having to remember to add a message

Overall I'd say that adds a lot of complexity.

Would a simpler solution be to make use of the hint text that's already supported and correctly-placed? The text you've injected does look like a hint.

**Comment by simcast** [comment]
Thanks for looking into this - it does seem too complex to be worth the change, we'll work around it in the service and try to use hint text as you suggested.

**Comment by peteryates** [comment]
I'm going to close this for now. Happy to revisit if a cleaner solution becomes apparent
