### ISSUE TITLE
How to set which item in a select collection is pre-selected?

### ISSUE THREAD

**Issue by david-mears** [DFE-Digital/govuk_design_system_formbuilder#153]
The Rails helper [options_for_select](https://apidock.com/rails/v4.0.2/ActionView/Helpers/FormOptionsHelper/options_for_select) takes a second argument which specifies which collection item is selected, allowing us to dynamically and automatically set it depending on e.g. the user's previous selection, saving them time.

I can't see a way to achieve the same outcome using GovUK Design System Formbuilder. This means that migrating our form to GovUK Design System Formbuilder would be a regression in user experience. Does a way exist to achieve this?

**Comment by peteryates** [comment]
Hi David. This is possible but your issue highlighted a shortfall in the docs which I've fixed in dbfdc6c0017.

I think the cleanest solution is to add your options to a _collection_ object and pass it into `#govuk_collection_select` along with the preselected `id` in the `options` hash. Example [here](https://github.com/DFE-Digital/govuk_design_system_formbuilder/commit/dbfdc6c00175de08ab80671f1cad71ec4850912b#diff-a4e26d561488657d0c0a4265de87815dR80).

Let me know how you get on. If for some reason this approach isn't suitable I think there would be a case for implemeting `#govuk_select` as a wrapper for [`#select`](https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-select).

**Comment by david-mears** [comment]
Setting `options: { selected: foo }` works a treat. Thank you. But I have now run up against the issue described here (I do not work on this product):

https://github.com/DFE-Digital/get-help-with-tech/blob/c74f8fda8d4e8b728a277ffc7649d72cbb0d8649/app/webpacker/styles/overrides.scss

Namely, I want to set the class of the resulting select, but something seems to eat the class option somewhere along the way.

I have tried adding `class: 'foo'` to `options` and to `html_options`.

**Comment by david-mears** [comment]
More specifically:

Currently, we apply classes and other attributes (e.g. `disabled`) to both the `.govuk-form-group` and the `select` it contains. 

That might cash out to two separate issues: one to be able to add classes to the containing div, and one to add attributes to the select.

We'd like to have both so we can replicate what we already have [here](https://github.com/DFE-Digital/teacher-vacancy-service/blob/8f9766601b28754f21057acf79c705b2c0571456/app/views/vacancies/_filters.html.haml#L12) (pre-GDS Formbuilder). Both are requirements for GDS Formbuilder to be usable in this case (we use it elsewhere on our service).

**Comment by peteryates** [comment]
Ah, classes supplied in `html_options` are [being overwritten](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/elements/select.rb#L39). That's clearly not correct, fix incoming.

I'm slightly reluctant to add support for setting classes on the form group, it's a much bigger change - we'd want consistent behaviour across all helpers that wrap their content in a [`FormGroup`](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/containers/form_group.rb).

However, if there's a widespread need for it, it can be done.

For the moment I'd suggest wrapping the `#govuk_collection_select` in an element that you can use to target the CSS:

```scss
.full-width-wrapper > .govuk-form-group {
  // blah
}
```
