### ISSUE TITLE
Add service start page submit button

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/govuk_design_system_formbuilder#172]
As per [GOV.UK Design System](https://design-system.service.gov.uk/components/button/), it would be nice to support the service start button in the FormBuilder.

I will find some time to work on this soon hopefully, but anybody feel free to make a start in the meantime.

**Comment by peteryates** [comment]
I remember looking into this when initially implementing `#govuk_submit` and opted against it because based on my (limited) research at the time, usually the start now buttons are styled links. They're usually there to direct people to the first page of a wizard.

If there's a want for it, I'm fine with having a `start` flag or something on the method to style it though 👍

**Comment by cpjmcquillan** [comment]
That makes sense, the reason I thought about adding it is because there is a need for it in the project I'm working on currently. 

If there isn't a wider need, I will try to achieve the same result with custom classes.

**Comment by peteryates** [comment]
Going to close this for now. Happy to reopen if there's a need. Also, this functionality is overlaps with the [components library start button](https://github.com/DFE-Digital/govuk-components/blob/master/app/components/govuk_component/start_now_button.rb) - example [here](https://dfe-digital.github.io/govuk-components/#start-now-button).
