### ISSUE TITLE
Single checkbox has suprising behaviour

### ISSUE THREAD

**Issue by tijmenb** [DFE-Digital/govuk_design_system_formbuilder#210]
Related to: https://github.com/DFE-Digital/apply-for-teacher-training/pull/3237#discussion_r510784350

We've built a couple of forms that look like this: 

```rb
<%= form_with model: @user do |f| %>
  <%= f.govuk_check_box :admin, true %>
  <%= f.govuk_submit 'Save' %>
<% end %>
```

A form like this will submit `params[:user][:admin] == "true"` - a string, not a boolean. 

Then, when you assign this value like `@user.admin = params[:user][:admin]` and render the form again, your checkbox will be unchecked, because it compares `"true"` to `true`.

```rb
<%= form_with model: User.new(admin: "true") do |f| %>
  <%= f.govuk_check_box :admin, true %>
  <%= f.govuk_submit 'Save' %>
<% end %>
```

Setting the `govuk_check_box` value to any other value will work - even `nil` because the `value` will be `"on"`. 

```rb
<%= form_with model: User.new(admin: "on") do |f| %>
  <%= f.govuk_check_box :admin, nil %>
  <%= f.govuk_submit 'Save' %>
<% end %>
```
I *think* we could compare the stringified version of the `value` to make this work out of the box? Otherwise, would raising an error be good?

**Comment by peteryates** [comment]
Thanks for reporting this @tijmenb. It's bitten a few people and is something that definitely needs attention. As a result of a similar query a while ago I changed the [guide entry for single checkboxes](https://govuk-form-builder.netlify.app/form-elements/checkboxes/#generating-a-single-checkbox) to use a `1` and `0`. I believe that setup should just work for single checkboxes.

Setting an unchecked value is important because it defaults to `false` which causes Rails _not_ to generate a hidden field for when the checkbox is unchecked; the fieldset also needs to be informed because for multiple checkboxes _it_ has the responsibility of generating the hidden field.

It's a bit of a headache, the docs can definitely be made clearer here though. If there's a silver bullet code fix I'd welcome the PR :smile:

**Comment by peteryates** [comment]
I think this is covered by the example in the guide, I've also added a link from the intro paragraph directly to the example to hopefully make it clearer. Willing to reopen and try to make it more intuitive if necessary but will close for the moment. Thanks.
