### ISSUE TITLE
Collection check boxes hint reverts to translation file even when hint is nil

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/govuk_design_system_formbuilder#212]
When specifying `hint: { text: nil }` as per [the docs](https://www.rubydoc.info/gems/govuk_design_system_formbuilder/GOVUKDesignSystemFormBuilder/Builder#govuk_collection_check_boxes-instance_method), the hint text should **not** be rendered, but instead it falls back to the translation `'helpers.hint.{form}.{attribute_name}'`. The current workaround is to ensure the translation isn't present

### Example
![image](https://user-images.githubusercontent.com/25187547/97680702-087d3180-1a8f-11eb-8c07-85d12305927b.png)

**Comment by peteryates** [comment]
Thanks for reporting this.

It looks like the problem is [here](https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/master/lib/govuk_design_system_formbuilder/traits/hint.rb#L18). The hint is just built as it would be when 'emtpy' and it then goes and populates its `@text` via the localisation mechanism.

At the point referenced above the hint should be initialised in a `disabled` state, making its `#html` method return nil and not affect the output. Legends, captions and labels should also have the same behaviour.

Not sure whether it's best to pass a `disabled: true` into the initializer _or_ try splitting off to a new `Elements::DisabledHint` class that will never produce any HTML.

**Comment by peteryates** [comment]
I've added #213 which I believe fixes the underlying issue. I think I need to revisit the docs too, because to suppress a hint altogether you'd need to pass `hint: nil`. To me, that feels like the most-logical way of _disabling_ the element. If any options are passed in other than `text:`, it suggests you want _something_ to be rendered.
