### ISSUE TITLE
Idea: custom data attributes on components

### ISSUE THREAD

**Issue by ethanmills** [DFE-Digital/govuk_design_system_formbuilder#249]
Would you be open to adding the ability to set custom data attributes on components? We're using `data-test` attributes for Cypress tests, and it would be great to be able to set them on formbuilder components. I would be happy to write a PR if that helps.

**Comment by peteryates** [comment]
Yeah, this is definitely something that should be supported consistently across the helpers. Some already support this behaviour by adding any extra keyword args as HTML attributes, but a couple of the mimic Rails' built-in `html_attributes`.

**Comment by peteryates** [comment]
I had a quick play with this and think the best route is to create a `Traits::HTMLAttribute` module that can be dropped in to any of the classes that would support this behaviour, which will probably be most (or all) of the `Elements`.

There's a slight inconsistency because `#govuk_select` mimics Rails' `html_options` arg instead of just using the keyword args for HTML attributes. I guess at this point the key choice is on the direction we take, add a `html_options` arg to the other helpers or allow `#govuk_select` to use the keyword args (and eventually deprecate `html_options`).

**Comment by ethanmills** [comment]
I suspect keyword args will lead to lower maintenance burden in the long run
