### ISSUE TITLE
Not able to check a govuk_radio_button value

### ISSUE THREAD

**Issue by vassyz** [DFE-Digital/govuk_design_system_formbuilder#274]
I'm using the `govuk_radio_button` on an edit page. It contains the nested attribute values for the model. I'd want to check the current selected value on a condition, but I can't find an attribute that works. I've tried with `checked`, but it seems it doesn't exist. Looked through the codebase and documentation and couldn't find anything. Is it not possible? Thanks.

**Comment by peteryates** [comment]
Yeah - it's definitely possible to set the checked option. I'd recommend setting the attribute on the model in the controller (or defaulting it to something) rather than in the view via an argument, though.

Here's a quick example:

```ruby
  # orders_controller.rb
  def new
    @order = Order.new
    @order.extra_topping_id = 2
  end
```

```erb
  <%= form.govuk_radio_buttons_fieldset(:extra_topping_id, legend: { text: "Select your toppings" }) do %>
    <%= form.govuk_radio_button(:extra_topping_id, 1, label: { text: "Ham" }) %>
    <%= form.govuk_radio_button(:extra_topping_id, 2, label: { text: "Pineapple 🍍" }) %>
    <%= form.govuk_radio_button(:extra_topping_id, 3, label: { text: "Sweetcorn" }) %>
  <% end %>
```

Result:

![Screenshot from 2021-05-04 15-41-57](https://user-images.githubusercontent.com/128088/117021462-47669b00-acef-11eb-839c-2663724d6c18.png)

**Comment by vassyz** [comment]
Thanks for your reply. Setting it in the controller is a bit tricky, because of the nested attributes. I'll look into it, maybe using a transient attribute. Unfortunately, the `checked` option doesn't seem to be available in the version I'm using: `1.2.0b1`

**Comment by peteryates** [comment]
Ah, yeah - since then the way extra args/keyword args are dealt with internally has been overhauled and standardised. I'd recommend upgrading, there aren't _too many_ breaking changes (and those that do are straightforward to fix). There's details on them in [the changelog](https://github.com/DFE-Digital/govuk_design_system_formbuilder/releases). I can assist if you hit any problems.

**Comment by peteryates** [comment]
Going to close this as I _think_ it's solved by moving to the latest version, happy to re-open if you need any assistance @vassyz

**Comment by vassyz** [comment]
Hi @peteryatesm, sorry for not replying quicker. Unfortunately, we are not able to upgrade the gem at this point in time. I tried doing it quickly, for testing purposes, and I got errors related to `hint_text` and the styling was a bit off. It will require some effort and it is not out biggest priority at the moment. Thank you again for your help!
