### ISSUE TITLE
Show/hide password button visibility

### ISSUE THREAD

**Issue by jjromeo** [DFE-Digital/govuk_design_system_formbuilder#504]
As discussed in [this issue](https://github.com/x-govuk/govuk-form-builder/issues/495). [The password input button](https://govuk-form-builder.netlify.app/form-elements/password-input/) should be optional / invisible when javascript is not enabled. That issue was closed as fixed but as per [my comment](https://github.com/x-govuk/govuk-form-builder/issues/495#issuecomment-2152853378) on the original issue the button is still visible with or without javascript enabled. From what I can tell `display: inline-block` overrides the `hidden: true` attribute and so this will need to be fixed in another way.

**Comment by peteryates** [comment]
Thanks for reporting @jjromeo.

I had a look and wasn't able to recreate the problem. I used the guide which has a pretty vanilla GOV.UK frontend setup, other than colour/font tweaks:

https://github.com/x-govuk/govuk-form-builder/assets/128088/4f6b4963-a7d0-4f5e-b2e9-d9306a3802c5


Are you sure the problem isn't caused by something in your app?

**Comment by peteryates** [comment]
Are you able to link to a review app? I'll take a look.
